### ISSUE TITLE
not working when using dotnet sdk 3.1.300

### ISSUE THREAD

**Issue by FuturistiCoder** [thomaslevesque/InternalsVisibleTo.MSBuild#3]
Hello,
Thanks for the nuget.
I updated dotnet sdk to 3.1.300 and it's not working anymore.

**Comment by thomaslevesque** [comment]
Hi @FuturistiCoder,

Thanks for the report. I was able to reproduce the problem with SDK 3.1.300.
This is strange, though... It works fine with 3.1.100, *and* with 5.0.100-preview.4, but not with 3.1.300, so I suspect a regression in the .NET SDK itself...

I'm looking into it.

**Comment by thomaslevesque** [comment]
Ah, I see.
They changed the target in which the AssemblyInfo.cs file is generated. It used to be done during `CoreCompile`, but now it's during `BeforeCompile`.
The `AddInternalsVisibleTo` target runs right before `CoreCompile`, so at this point the AssemblyInfo.cs file has already been generated and it's too late to add new attributes.

I'll move it to BeforeCompile, which hopefully should still work for other SDK versions

**Comment by thomaslevesque** [comment]
I just pushed a new version to NuGet, it should fix the problem.

**Comment by thomaslevesque** [comment]
Did that fix the problem for you @FuturistiCoder?

**Comment by FuturistiCoder** [comment]
> Did that fix the problem for you @FuturistiCoder?

Thanks for the fix. I'm using old style for now, and waiting for Net5. https://github.com/dotnet/sdk/pull/3439
cause I don't know whether they will change it recently.

**Comment by thomaslevesque** [comment]
> waiting for Net5. [dotnet/sdk#3439](https://github.com/dotnet/sdk/pull/3439)

Ah, I wasn't aware of this. So I guess this library will become useless in .NET 5... I'll probably need to do something (don't emit the attributes, and maybe emit a warning) when using .NET 5 SDK, otherwise it will cause conflicts.

**Comment by thomaslevesque** [comment]
For future reference, the change that caused the issue was https://github.com/dotnet/sdk/issues/10614.
