### ISSUE TITLE
Using `InternalsVisibleTo` MSBuild items is now supported out of the box by the .NET SDK

### ISSUE THREAD

**Issue by 0xced** [thomaslevesque/InternalsVisibleTo.MSBuild#6]
Since .NET 5, using `InternalsVisibleTo` MSBuild items is [supported out of the box](https://github.com/dotnet/sdk/blob/v5.0.102/src/Tasks/Microsoft.NET.Build.Tasks/targets/Microsoft.NET.GenerateAssemblyInfo.targets#L108-L112) thanks to https://github.com/dotnet/sdk/pull/3439.

I think it would be worth mentioning it in the README in order to avoid potential confusion.

**Comment by thomaslevesque** [comment]
Hi @0xced,

Thanks for the heads up! I had no idea this had been added to the SDK itself. This is great news!
I'll update the README. While I'm at it, I should probably try to warn the user if they have this package installed when using the .NET 5 SDK... Not sure if it's possible, but I'll look into it.

**Comment by thomaslevesque** [comment]
> I had no idea this had been added to the SDK itself

Looks like my memory failed me. This had already be mentioned here: https://github.com/thomaslevesque/InternalsVisibleTo.MSBuild/issues/3#issuecomment-633627226

**Comment by thomaslevesque** [comment]
I updated the README and published a new version of the package. It emits the following warning if the SDK version is 5.0 or greater:

> Starting with version 5.0, the .NET SDK has built-in support for InternalsVisibleTo. The functionality provided by the InternalsVisibleTo.MSBuild package has been disabled to avoid conflicts. You should uninstall this package; note that with the .NET SDK feature, the public key is specified in a separate 'Key' attribute, instead of being appended to the assembly name in the 'Include' attribute.
